export type { BookSpec, BookshelfProps } from './Bookshelf'
export { Bookshelf } from './Bookshelf'
export type { ChairProps } from './Chair'
export { Chair } from './Chair'
export type { ClockProps } from './Clock'
export { Clock } from './Clock'
export type { DoorProps } from './Door'
export { Door } from './Door'
export type { FloorProps } from './Floor'
export { Floor } from './Floor'
export type { GrassProps } from './Grass'
export { Grass } from './Grass'
export type { HouseProps } from './House'
export { House } from './House'
export type { LakeProps } from './Lake'
export { Lake } from './Lake'
export type { LampProps } from './Lamp'
export { Lamp } from './Lamp'
export type { LightRigProps } from './LightRig'
export { LightRig } from './LightRig'
export type { PlayerProps, PlayerView } from './Player'
export { Player } from './Player'
export type { RocksProps } from './Rocks'
export { Rocks } from './Rocks'
export type { RoofProps, RoofStyle } from './Roof'
export { Roof } from './Roof'
export type { RoomProps } from './Room'
export { Room } from './Room'
export type { RugProps } from './Rug'
export { Rug } from './Rug'
export { registry } from './registry'
export type { ShelfProps } from './Shelf'
export { Shelf } from './Shelf'
export type { ShoreProps } from './Shore'
export { Shore } from './Shore'
export type { SkyProps } from './Sky'
export { Sky } from './Sky'
export type { StaircaseProps } from './Staircase'
export { Staircase } from './Staircase'
export type { TableProps } from './Table'
export { Table } from './Table'
export type { TerrainProps } from './Terrain'
export { Terrain } from './Terrain'
export type { TreesProps } from './Trees'
export { Trees } from './Trees'
export type { WallOpening, WallProps } from './Wall'
export { Wall } from './Wall'
export type { WindowProps } from './Window'
export { Window } from './Window'
